name: Flutter Checks

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: beta
          flutter-version: "3.41.0-0.2.pre"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Install matcher
        run: echo "::add-matcher::.github/analyzer-problem-matcher.json"

      - name: Run flutter analyze
        shell: bash
        run: |
          flutter analyze | tee ./flutter_analyze_report.txt

      - name: Remove matcher
        if: always()
        run: echo "::remove-matcher owner=dart-analyzer::"

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        if: always()
        with:
          ruby-version: "2.7"
          bundler-cache: true

      - name: Danger
        uses: MeilCli/danger-action@1996610a4c089e3a79bf3131a70c3c1b311e32f9
        if: always()
        with:
          plugins_file: "Gemfile"
          install_path: "vendor/bundle"
          danger_file: "Dangerfile"
          danger_id: "danger-pr"
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # test:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Install Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: beta
  #         flutter-version: "3.41.0-0.2.pre"
  #         cache: true

  #     - name: Run flutter pub get
  #       run: flutter pub get

  #     - name: Run flutter test
  #       run: flutter test

  # usageを消費しすぎるためコメントアウト
  # build:
  #   strategy:
  #     matrix:
  #       include:
  #         - target: appbundle
  #           runs-on: ubuntu-latest
  #         - target: ios
  #           runs-on: macos-latest
  #         - target: web
  #           runs-on: ubuntu-latest
  #   runs-on: ${{ matrix.runs-on }}
  #   timeout-minutes: 30
  #   concurrency:
  #     group: ${{ github.workflow }}-${{ github.ref }}-${{ github.job }}-${{ matrix.target }}-${{ matrix.runs-on }}
  #     cancel-in-progress: true
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Install Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: stable
  #         flutter-version: "3.38.9"
  #         cache: true

  #     - name: Run flutter pub get
  #       run: flutter pub get

  #     - name: Build APK
  #       run: flutter build ${{ matrix.target }}
